# Generated by Django 4.1.4 on 2022-12-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'sub Categories'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='cover_image',
            new_name='cover',
        ),
    ]
